# Generated by Django 3.2.3 on 2021-05-24 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudApp', '0002_post_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='writer',
            field=models.CharField(default='닉네임을 입력해주세요', max_length=15),
        ),
    ]
